-- Synthetic Alpha 0.12.8 schema for isolated migration tests only.
-- It contains representative rows but no reusable credential, token, webhook or project ID.

do $fixture_roles$
begin
  if not exists (select 1 from pg_catalog.pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_catalog.pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_catalog.pg_roles where rolname = 'service_role') then
    create role service_role nologin;
  end if;
end;
$fixture_roles$;

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

grant usage on schema public to anon, authenticated, service_role;

create table public.joueurs (
  id bigint generated by default as identity primary key,
  pseudo text not null,
  roles text not null default 'Soldat',
  statut text not null default 'Actif',
  mot_de_passe text,
  mot_de_passe_modifie boolean not null default false,
  date_ajout timestamptz not null default now(),
  derniere_connexion timestamptz,
  derniere_modification timestamptz not null default now(),
  discord_id text,
  discord_username text,
  discord_lie_a timestamptz,
  constraint joueurs_pseudo_key unique (pseudo)
);

create table public.competitions (
  id bigint generated by default as identity primary key,
  nom text not null,
  statut text not null default 'Brouillon',
  date_creation timestamptz not null default now(),
  cree_par text not null default 'Fixture',
  roles_autorises text not null default 'Soldat',
  description text not null default '',
  fermeture_auto_active boolean not null default false,
  heure_ouverture text,
  heure_fermeture text,
  dernier_traitement_auto date,
  notification_presence_active boolean not null default false,
  heure_notification_presence text,
  rappel_presence_active boolean not null default false,
  heure_rappel_presence text
);

create table public.dates_competition (
  id bigint generated by default as identity primary key,
  competition_id bigint,
  date_competition date not null,
  horaires text not null default '',
  constraint dates_competition_competition_id_fkey
    foreign key (competition_id) references public.competitions(id) on delete cascade
);

create table public.presences (
  id bigint generated by default as identity primary key,
  competition_id bigint,
  pseudo text not null,
  date_competition date not null,
  statut text not null default 'Non renseigne',
  horaires_disponibles text not null default '',
  derniere_modification timestamptz not null default now(),
  constraint presences_competition_id_pseudo_date_competition_key
    unique (competition_id, pseudo, date_competition)
);

create table public.journal_activite (
  id bigint generated by default as identity primary key,
  date_heure timestamptz not null default now(),
  utilisateur text not null,
  action text not null,
  details text not null default ''
);

create table public.rappels_presence_discord (
  id bigint generated by default as identity primary key,
  type_rappel text not null,
  competition_id bigint not null,
  date_competition date not null,
  heure_programmee time,
  statut text not null default 'envoye',
  envoye_a timestamptz not null default now(),
  erreur text,
  nb_joueurs integer not null default 0,
  nb_mentions integer not null default 0,
  nb_sans_discord integer not null default 0,
  nb_messages integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.discord_link_requests (
  id uuid primary key default extensions.gen_random_uuid(),
  joueur_id bigint,
  pseudo text not null,
  code_hash text,
  discord_id text,
  discord_username text,
  statut text not null default 'code_genere',
  expires_at timestamptz not null,
  used_at timestamptz,
  validated_at timestamptz,
  validated_by text,
  refused_at timestamptz,
  refused_by text,
  reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_joueurs_pseudo on public.joueurs (pseudo);
create index idx_joueurs_discord_id on public.joueurs (discord_id);
create index idx_journal_activite_date_heure on public.journal_activite (date_heure desc);
create index idx_dates_competition_competition_date
  on public.dates_competition (competition_id, date_competition);
create index idx_dates_competition_competition_id
  on public.dates_competition (competition_id);
create index idx_presences_competition_pseudo_date
  on public.presences (competition_id, pseudo, date_competition);
create index idx_presences_competition_pseudo
  on public.presences (competition_id, pseudo);
create index idx_presences_pseudo on public.presences (pseudo);
create unique index idx_rappels_presence_discord_unique
  on public.rappels_presence_discord (
    type_rappel, competition_id, date_competition, heure_programmee
  );

alter table public.joueurs enable row level security;
alter table public.competitions enable row level security;
alter table public.dates_competition enable row level security;
alter table public.presences enable row level security;
alter table public.journal_activite enable row level security;
alter table public.rappels_presence_discord enable row level security;
alter table public.discord_link_requests enable row level security;

create policy "Public read joueurs" on public.joueurs
  for select to anon, authenticated using (true);
create policy "Public read competitions" on public.competitions
  for select to anon, authenticated using (true);
create policy "Public read dates_competition" on public.dates_competition
  for select to anon, authenticated using (true);
create policy "Public read presences" on public.presences
  for select to anon, authenticated using (true);
create policy "Public read journal_activite" on public.journal_activite
  for select to anon, authenticated using (true);
create policy "Public read rappels_presence_discord" on public.rappels_presence_discord
  for select to anon, authenticated using (true);

grant select on public.competitions to anon, authenticated;
grant select on public.dates_competition to anon, authenticated;
grant select on public.presences to anon, authenticated;
grant select on public.journal_activite to anon, authenticated;
grant select on public.rappels_presence_discord to anon, authenticated;
grant select (
  id, pseudo, roles, statut, discord_id, discord_username, discord_lie_a,
  derniere_connexion
) on public.joueurs to anon, authenticated;

insert into public.joueurs (pseudo, roles, statut, mot_de_passe)
values
  ('Fixture Player', 'Soldat', 'Actif', null),
  (
    'Fixture SuperAdmin',
    'SuperAdmin',
    'Actif',
    encode(extensions.gen_random_bytes(32), 'hex')
  );

insert into public.competitions (
  nom, statut, cree_par, roles_autorises, description,
  notification_presence_active, heure_notification_presence,
  rappel_presence_active, heure_rappel_presence
) values (
  'Fixture Competition', 'Ouverte', 'Fixture', 'Soldat',
  'Synthetic migration fixture', true, '19:00', true, '17:00'
);

insert into public.dates_competition (competition_id, date_competition, horaires)
select id, date '2030-01-15', '21:00,21:15'
from public.competitions where nom = 'Fixture Competition';

insert into public.presences (
  competition_id, pseudo, date_competition, statut, horaires_disponibles
)
select id, 'Fixture Player', date '2030-01-15', 'Absent', ''
from public.competitions where nom = 'Fixture Competition';

insert into public.rappels_presence_discord (
  type_rappel, competition_id, date_competition, heure_programmee, statut,
  nb_messages, erreur, updated_at
)
select
  rappel.type_rappel,
  c.id,
  date '2030-01-15',
  rappel.heure_programmee,
  rappel.statut,
  rappel.nb_messages,
  rappel.erreur,
  rappel.updated_at
from public.competitions c
cross join (values
  ('sans_reponse_17h', time '17:00', 'echec', 0, 'TEST_SYNTHETIQUE', timestamptz '2030-01-15 17:01:00+00'),
  ('presence_sans_reponse', time '17:00', 'envoye', 1, null, timestamptz '2030-01-15 17:02:00+00'),
  ('presence_staff', time '19:00', 'envoye', 1, null, timestamptz '2030-01-15 19:01:00+00')
) as rappel(type_rappel, heure_programmee, statut, nb_messages, erreur, updated_at)
where c.nom = 'Fixture Competition';
